name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analyse Pylint
        run: |
          pylint --rcfile config/.pylintrc app/

      - name: Exécution des tests unitaires
        run: |
          python -m pytest tests/

      - name: Scan de sécurité Bandit
        run: |
          bandit -c config/bandit.yaml -r app/

      - name: Audit de sécurité des dépendances
        run: |
          pip install pip-audit
          pip-audit
